site_name: 数学分享站
site_url: https://mathcourse-share.github.io
repo_url: https://github.com/mathcourse-share/mathcourse-share.github.io
repo_name: courseshare
copyright: Copyright © 2025 [mathcourse-share]

theme:
  name: material
  custom_dir: overrides
  language: zh

  favicon: assets/logo.png
  logo: assets/logo.png

  palette:
    - scheme: default    # Palette toggle for light mode
      toggle:
        icon: material/brightness-7 
        name: 启动暗影模式

    - scheme: slate    # Palette toggle for dark mode
      toggle:
        icon: material/brightness-4
        name: 开启日光模式

  primary: indigo    # 主色调
  accent: pink      # 强调色
  font: 
    text: Noto Sans SC
    code: Roboto Mono

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    annotation: material/arrow-right-circle
  features:
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.instant


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/consent.js

# 扩展css
extra_css:
  - stylesheets/extra.css

# cookie
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      extra:
    actions:
      - accept
      - reject
      - manage




# encrypt
plugins:
    - search: {}
    - encryptcontent:
        password_inventory:
          classified: 'password1'
          confidential:
            - 'password2'
            - 'password3'
          secret:
            keran: 'CYX'
            user5: 'password5'

# 页面
nav:
  - Home:
      - index.md
      - about.md
  - course:
      - how-to-learn&solve-question.md
      - course.md
  - Blogs:
      - index: Blogs/index.md
      - Archives: Blogs/archives.md
      - Posts:
          - Blogs/posts/24-12-29.md
          - Blogs/posts/24-12-30.md
          - Blogs/posts/25-01-20.md
          - Blogs/posts/FreeSplatter 代码解读.md
          - Blogs/posts/Gaussian_Splatting_Code.md
          - Blogs/posts/Gaussian_Splatting_复现.md
          - Blogs/posts/OCRN.md
          - Blogs/posts/ULIP-2.md
          - Blogs/posts/用AI后的问题.md
          - Blogs/posts/notes_software.md
  - Summaries:
      - Summaries/index.md
      - Weekly:
          - 2024:
              - Summaries/2024/weekly/2024-W44-10.md
              - Summaries/2024/weekly/2024-W45-11.md
              - Summaries/2024/weekly/2024-W46-11.md
              - Summaries/2024/weekly/2024-W47-11.md
              - Summaries/2024/weekly/2024-W48-11.md
              - Summaries/2024/weekly/2024-W49-12.md
              - Summaries/2024/weekly/2024-W50-12.md
              - Summaries/2024/weekly/2024-W51-12.md
              - Summaries/2024/weekly/2024-W52-12.md
          - 2025:
              - Summaries/2025/weekly/2025-W01-12.md
              - Summaries/2025/weekly/2025-W02-01.md
              - Summaries/2025/weekly/2025-W03-01.md
              - Summaries/2025/weekly/2025-W04-01.md
              - Summaries/2025/weekly/2025-W05-01.md
      - Semesters:
          - Summaries/Semesters/202409-10.md
          - Summaries/Semesters/2024_1_1.md
          - Summaries/Semesters/2024summer_vacation.md
  - Computer Basic:
      - CS_Basic/index.md
      - CSAPP: CS_Basic/15-213/CSAPP.md
      - C++:
          - CS_Basic/C++/Accelerated C++.md
          - CS_Basic/C++/C++ Basic.md
      - CS61:
          - CS_Basic/CS61A/CS61A.md
          - CS_Basic/CS61A/Composing_Programs.md
          - CS_Basic/CS61C/计算机组成与设计硬件软件接口.md
      - Network:
          - CS_Basic/Network/Security.md
  - AI:
      - AI/index.md
      - Basic:
          - AI/Dive_into_Deep_Learning.md
          - AI/SLAM14.md
          - AI/统计学习方法.md
      - CS231n:
          - AI/CS231n/CS231n_notes.md
          - AI/CS231n/Image Classification-Data-driven Approach, k-Nearest Neighbor, train_val_test splits.md
          - AI/CS231n/Linear classification-Support Vector Machine, Softmax.md
          - AI/CS231n/Numpy.md
      - EECS 498-007:
          - AI/EECS 498-007/KNN.md
          - AI/EECS 498-007/Pytorch.md
          - AI/EECS 498-007/linear_classifer.md
      - FFB6D:
          - AI/FFB6D/FFB6D_Conda.md
          - AI/FFB6D/FFB6D_Docker.md
  - Robot:
      - Robot/index.md
      - Robot/calibration.md
      - Robot/kalman.md
      - Robot/pnp.md
  - Tools:
      - Tools/index.md
      - Cheat Sheet:
          - Tools/Cheat Sheet/index.md
          - tools:
              - Tools/Cheat Sheet/tools/adb Cheat Sheet.md
              - Tools/Cheat Sheet/tools/bash Cheat Sheet.md
              - Tools/Cheat Sheet/tools/ffmpeg Cheat Sheet.md
              - Tools/Cheat Sheet/tools/gdb Cheat Sheet.md
              - Tools/Cheat Sheet/tools/git Cheat Sheet.md
              - Tools/Cheat Sheet/tools/ip Cheat Sheet.md
              - Tools/Cheat Sheet/tools/tmux Cheat Sheet.md
          - editors:
              - Tools/Cheat Sheet/editors/emacs Cheat Sheet.md
              - Tools/Cheat Sheet/editors/nano Cheat Sheet.md
              - Tools/Cheat Sheet/editors/org Cheat Sheet.md
              - Tools/Cheat Sheet/editors/vim Cheat Sheet.md
          - languages:
              - Tools/Cheat Sheet/languages/javascript Cheat Sheet.md
              - Tools/Cheat Sheet/languages/python Cheat Sheet.md
              - Tools/Cheat Sheet/languages/vimscript Cheat Sheet.md
      - AI:
          - Tools/AI/prompt.md
          - Tools/AI/prompt_writing.md
      - Blog:
          - Tools/Blog/Mkdocs_Material.md
      - Environment:
          - Tools/Environment/Ubuntu_setup.md
          - Tools/Environment/environment.md
          - Tools/Environment/obsidian_setup.md
      - Make:
          - Tools/Make/CMake.md
          - Tools/Make/Makeflie.md
      - Others:
          - Tools/Others/Chezmoi.md
          - Tools/Others/SSH.md
          - Tools/Others/zotero_使用指南.md
      - Terminal:
          - Tools/Terminal/Tabby_Zsh.md
  - Tags:
      - Tags/index.md

